// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseApp():Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function IsProduction():Promise<boolean>;

export function OpenURL(arg1:string):Promise<void>;

export function SetTitle(arg1:string):Promise<void>;
