// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['Service']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['Service']['Disconnect']();
}

export function ForwardToController(arg1) {
  return window['go']['main']['Service']['ForwardToController'](arg1);
}

export function ForwardToRouter(arg1) {
  return window['go']['main']['Service']['ForwardToRouter'](arg1);
}

export function GetLoadingLogs(arg1) {
  return window['go']['main']['Service']['GetLoadingLogs'](arg1);
}

export function GetLogs(arg1) {
  return window['go']['main']['Service']['GetLogs'](arg1);
}

export function GetQRCode(arg1) {
  return window['go']['main']['Service']['GetQRCode'](arg1);
}

export function GetRoutersAndAccessPoints() {
  return window['go']['main']['Service']['GetRoutersAndAccessPoints']();
}

export function GetState() {
  return window['go']['main']['Service']['GetState']();
}

export function OpenFileDialogForRouterFile(arg1) {
  return window['go']['main']['Service']['OpenFileDialogForRouterFile'](arg1);
}

export function ResetEverything() {
  return window['go']['main']['Service']['ResetEverything']();
}

export function SetConfig(arg1) {
  return window['go']['main']['Service']['SetConfig'](arg1);
}

export function Switch(arg1) {
  return window['go']['main']['Service']['Switch'](arg1);
}

export function SwitchRouter(arg1) {
  return window['go']['main']['Service']['SwitchRouter'](arg1);
}
