// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['Service']['Connect'](arg1);
}

export function DisableAllBlocklists() {
  return window['go']['main']['Service']['DisableAllBlocklists']();
}

export function DisableBlocklist(arg1) {
  return window['go']['main']['Service']['DisableBlocklist'](arg1);
}

export function DisableDNSWhitelist() {
  return window['go']['main']['Service']['DisableDNSWhitelist']();
}

export function Disconnect() {
  return window['go']['main']['Service']['Disconnect']();
}

export function EnableAllBlocklists() {
  return window['go']['main']['Service']['EnableAllBlocklists']();
}

export function EnableBlocklist(arg1) {
  return window['go']['main']['Service']['EnableBlocklist'](arg1);
}

export function EnableDNSWhitelist() {
  return window['go']['main']['Service']['EnableDNSWhitelist']();
}

export function ForwardToController(arg1) {
  return window['go']['main']['Service']['ForwardToController'](arg1);
}

export function ForwardToRouter(arg1) {
  return window['go']['main']['Service']['ForwardToRouter'](arg1);
}

export function GetLoadingLogs(arg1) {
  return window['go']['main']['Service']['GetLoadingLogs'](arg1);
}

export function GetLogs(arg1) {
  return window['go']['main']['Service']['GetLogs'](arg1);
}

export function GetQRCode(arg1) {
  return window['go']['main']['Service']['GetQRCode'](arg1);
}

export function GetRoutersAndAccessPoints(arg1) {
  return window['go']['main']['Service']['GetRoutersAndAccessPoints'](arg1);
}

export function GetState() {
  return window['go']['main']['Service']['GetState']();
}

export function LoadRoutersUnAuthenticated() {
  return window['go']['main']['Service']['LoadRoutersUnAuthenticated']();
}

export function OpenFileDialogForRouterFile(arg1) {
  return window['go']['main']['Service']['OpenFileDialogForRouterFile'](arg1);
}

export function RebuildDomainBlocklist() {
  return window['go']['main']['Service']['RebuildDomainBlocklist']();
}

export function ResetEverything() {
  return window['go']['main']['Service']['ResetEverything']();
}

export function SetConfig(arg1) {
  return window['go']['main']['Service']['SetConfig'](arg1);
}

export function StartDNSCapture() {
  return window['go']['main']['Service']['StartDNSCapture']();
}

export function StopDNSCapture() {
  return window['go']['main']['Service']['StopDNSCapture']();
}

export function Switch(arg1) {
  return window['go']['main']['Service']['Switch'](arg1);
}

export function SwitchRouter(arg1) {
  return window['go']['main']['Service']['SwitchRouter'](arg1);
}
